#!/bin/bash

{
  set -e
  set -o pipefail
  shopt -s inherit_errexit

  [ $# -lt 2 ] && echo "Usage: ${0##*/} SOURCE COMPILER [FLAG]..." >&2 && exit 1

  SOURCE="$1"
  shift

  # Из-за багов gcc и clang использовать -MM -MG невозможно

  my_grep(){
    if grep "$@"; then
      :
    else
      if [ $? = 1 ]; then
        :
      else
        return 2
      fi
    fi
  }

  COMPILE=false
  OUT="${SOURCE%.*}.o"

  process(){
    local REGEX='^ *# *include +"([^/].*)" *$'
    NON_LOCAL_HEADERS="$(my_grep -E "$REGEX" "$1" | sed -E "s~$REGEX~\\1~" | my_grep -vE ' ')"
    local HEADERS="$NON_LOCAL_HEADERS"
    for NON_LOCAL_INCLUDE in $HEADERS; do
      local INCLUDE="$NON_LOCAL_INCLUDE"
      if printf '%s\n' "$1" | grep -q /; then
        local FULL="${1%/*}/$INCLUDE"
      else
        local FULL="$INCLUDE"
      fi
      make "$FULL"
      if ! [ -f "$FULL" ]; then
        echo "${0##*/}: $FULL: not found, make didn't create it" >&2
        exit 1
      fi
      if [ -f "$OUT" ]; then
        if [ "$FULL" -nt "$OUT" ]; then
          COMPILE=true
        fi
      else
        COMPILE=true
      fi
      process "$FULL"
    done
    :
  }

  process "$SOURCE"
  "$COMPILE" && "$@" -c "$SOURCE"
  exit 0
}
